apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  labels:
    app: mysql-exporter
spec:
  ports:
    - port: 9104
      targetPort: 9104
  selector:
    app: mysql-exporter
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-exporter
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  strategy:
    rollingUpdate:  
      maxSurge: 1
      #滚动升级时会先启动1个pod
      maxUnavailable: 0
      #最大不可用个数，也可以写百分比
  selector:
    matchLabels:
      tier: mysql-exporter
      #选择使用的模板
  template:
    metadata:
      labels:
        tier: mysql-exporter
    spec:
      containers:
      - image: registry.chinadaas.com/library/mysqld-exporter
        name: mysql-exporter
        args: ["-collect.binlog_size=true","-collect.info_schema.processlist=true"]
        env:
         - name: DATA_SOURCE_NAME
           value: "root:Chinadaas@mysql@(192.168.206.156:3306)/platform"
        ports:
        - containerPort: 9104
          name: mysql-exporter
        livenessProbe:
          tcpSocket:
            port: 9104
          #检测端口是否存活
          initialDelaySeconds: 30
          timeoutSeconds: 10   
        readinessProbe:
          tcpSocket:
            port: 9104
          initialDelaySeconds: 30
          successThreshold: 1
