apiVersion: v1
kind: Service
metadata:
  name: grafana-zabbix
  labels:
    myapp: grafana-zabbix
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 3000
  selector:
    myapp: grafana-zabbix
